config/routes.rb
GplusRailsDemo::Application.routes.draw do

  resources :users do
    member do
      get 'profile'
      get 'activities'
    end
  end

  match 'oauth/callback' => 'oauth#callback'

  root :to => 'site#index'
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  # Setup a Gplus::Client for making public (non-authorized) requests, or for requesting authorization to access a user's data
  def setup_gplus
    @gplus = Gplus::Client.new(
      :api_key => GPLUS_CONFIG['api_key'],
      :client_id => GPLUS_CONFIG['client_id'],
      :client_secret => GPLUS_CONFIG['client_secret'],
      :redirect_uri => GPLUS_CONFIG['redirect_uri']
    )
  end

  # Setup a Gplus::Client authorized to use the specified user's stored OAuth token
  def setup_authorized_gplus(user)
    setup_gplus
    access_token = @gplus.authorize(user.token, user.refresh_token, user.token_expires_at)

    # Check if the access token was implicitly refreshed
    # If it was, store the user's new token and the time that it expires at
    if @gplus.access_token_refreshed?
      user.update_attributes(:token => access_token.token, :token_expires_at => access_token.expires_at)
    end
  end
end

app/controllers/oauth_controller.rb
class OauthController < ApplicationController
  before_filter :setup_gplus

  # Handle OAuth callbacks from Google+
  def callback
    # Take the short-lived :code, and use it to get a proper access_token from Google+
    access_token = @gplus.get_token(params[:code])

    # Store the access_token so that we can use it later to access the user's information
    @user = User.new(
      :token => access_token.token,
      :refresh_token => access_token.refresh_token,
      :token_expires_at => access_token.expires_at
    )

    @user.save
    redirect_to @user
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_filter :setup_gplus

  def index
    # Generate an authorization URL
    @auth_url = @gplus.authorize_url

    # Generate an authorization URL that requests offline access.
    # Note that offline access is required to be able to refresh a user's OAuth token.
    # Otherwise, you can only access their data until their token expires (currently 1 hour).
    @offline_auth_url = @gplus.authorize_url(:access_type => 'offline')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :get_user

  def show
  end

  def profile
    # Get the person that Gplus is authorized as
    @profile = @gplus.get_person('me')

    # Do a search for people with the same name, limited to 3 results
    @search_results = @gplus.search_people(@profile['displayName'], :maxResults => 3)

    # Get additional results for people with the same name, using the :pageToken option and the 'nextPageToken' from the previous search results
    @more_search_results = @gplus.search_people(@profile['displayName'], :maxResults => 3, :pageToken => @search_results['nextPageToken'])
  end

  def activities
    # List the activities for the person that Gplus is authorized as
    @activities = @gplus.list_activities('me')

    # List the comments for the person's last activity
    @comments = @gplus.list_comments(@activities['items'].last['id'])

    # Find a specific comment
    @last_comment = @gplus.get_comment(@comments['items'].last['id'])

    # List the people who +1'd the person's last activity
    @plusoners = @gplus.list_people_by_activity(@activities['items'].last['id'], 'plusoners')

    # List the people who reshared the person's last activity
    @resharers = @gplus.list_people_by_activity(@activities['items'].last['id'], 'resharers')
  end

private
  def get_user
    @user = User.find(params[:id])

    # Call setup_authorized_gplus method in ApplicationController, to initialize a Gplus::Client with the user's stored OAuth token
    setup_authorized_gplus(@user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GplusRailsDemo</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/site/index.html.erb
<h1>gplus demo</h1>

<%= link_to 'Log in with Google+', @auth_url %>
<br />
<%= link_to 'Log in with Google+ (with offline access)', @offline_auth_url %>

app/views/users/activities.html.erb
<h1><%= link_to "User #{@user.id}", @user %></h1>

<p>
  <b>My activities:</b>
  <br />
  <%= @activities %>
</p>

<p>
  <b>Comments on my activities:</b>
  <%= @comments %>
</p>

<p>
  <b>The last comment on my activities, found by id:</b>
  <%= @last_comment %>
</p>

<p>
  <b>The people who +1'd my last activity:</b>
  <%= @plusoners %>
</p>

<p>
  <b>The people who reshared my last activity:</b>
  <%= @resharers %>
</p>

app/views/users/profile.html.erb
<h1><%= link_to "User #{@user.id}", @user %></h1>

<p>
  <b>My profile:</b>
  <br />
  <%= @profile %>
</p>

<p>
  <b>People with the same name as me:</b>
  <br />
  <%= @search_results %>
</p>

<p>
  <b>Another page of people with the same name as me:</b>
  <br />
  <%= @more_search_results %>
</p>

app/views/users/show.html.erb
<h1>User <%= @user.id %></h1>

<%= link_to 'My Google+ profile', profile_user_path(@user) %>
<%= link_to 'My Google+ activities', activities_user_path(@user) %>